# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d6012c5795cefa00926cc29c5769b6a49413af3cafdfb979b1cc9a9882f2e45f9de9ca3c43a0a1e3ba78317420d136f78f343a730b4faf2dda023c1b3dd07a4

test:
  secret_key_base: ca69c61726e47e43bbe785ee42bfb95e6ba8436303b79199742999f7cbfe38e480cf4a8a98c07f67b8a41d7b47468f4f68a5fd15adcf16ec559758a119900d1c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
